version: '3'

services: 
  web: 
    build: . 
    ports: 
      - "5000:5000"
    depends_on: 
     - db 
    environment:  
     - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase

  db: 
    image: postgres:13 
    environment: 
      POSTRES_USER: myuser
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_DB: mydatabase
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes: 
  postgres_data: 
